#!/bin/python3

import os
import sys
import time

#
# Complete the timeConversion function below.
#

def timeConversion(s):
    lngth = len(s)
    AM ='AM'
    if AM in s:
        hour, minute, second = s[0:lngth-2].split(":")
        if hour == '12':
            hour = '00'
        s=hour + ":" + minute + ":" + second
        return s
    else:
        hour, minute, second = s[0:lngth-2].split(":")
        if hour != '12':
            hour = str(int(hour) + 12)
        s=hour + ":" + minute + ":" + second
        return s
    

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    f.write(result + '\n')

    f.close()
