#!/bin/python3

 

import os

import sys

 

#

# Complete the simpleArraySum function below.

#

def simpleArraySum(ar):

    #

    # Write your code here.

    #

    sum=0

    for index in ar:

        sum += index

    return sum

    

 

if name == 'main':

    fptr = open(os.environ['OUTPUT_PATH'], 'w')

 

    ar_count = int(input())

 

    ar = list(map(int, input().rstrip().split()))

 

    result = simpleArraySum(ar)

 

    fptr.write(str(result) + '\n')

 

    fptr.close()

 
